### ISSUE TITLE
Fatal Frame v1.0.0.0 Captures Screenshot at Every Login

### ISSUE THREAD

**Issue by Sunhealer** [Glyceri/XivFatalFrame#2]
**Issue:**
When I log into my character, while in the loading screen, Fatal Frame takes a screenshot, which is not expected behaviour.

**Steps to reproduce**

1. Have "Take Screenshot On Item Unlocked" enabled
2. Log into any character
3. A screenshot is taken

**Additional Notes**

Fatal Frame outputs the following in the Log Window when taking the screenshot:

> Fatal Frame took a Screenshot. [ItemUnlocked]

**Comment by Glyceri** [comment]
How weird 🤔 it didn't used to do that. I'll put it on the TODO list, but I currently dont have an active sub to test it. This might be an issue with CS, since I hook directly into that.

**Comment by Glyceri** [comment]
It turns out the way everyone gathered framerkit data was wrong, this includes me. Framerkits should use `item.AdditionalData.RowId` instead of `ItemAction.Value.Data[0]`. This also breaks Acquisition Date.

I don't have a sub so I find it hard to test this currently, but I will get around to it soon.

**Comment by Sunhealer** [comment]
Ah I see, nice 👍 

You could pop the change into a beta release, I'd be happy to test it then.

**Comment by Glyceri** [comment]
I have pushed a fix earlier today! I hope this has fixed it, if not tell me, then I shall buy a sub and actually fix the issue.

**Comment by Sunhealer** [comment]
Hey! Sorry about the late response, was on vacation so I couldn't test the fix.

Sadly though, it seems like version 1.0.1.0 still takes a screenshot during the loading screen, so your fix has not resolved the issue.

**Comment by Glyceri** [comment]
Tragic, I will see to fixing it

**Comment by Glyceri** [comment]
I cannot seem to replicate this issue. It doesnt trigger for me so I dont know what item causes it. 

I could be VERY crude and disable screenshots being taken within 0.5 seconds of logging in but thats not a real solution.

**Comment by Glyceri** [comment]
Or I just call the Reset() function upon login which I forgot to do...

**Comment by Sunhealer** [comment]
I'll try and remove all items from my inventory and see if the issue persists.

**Comment by Sunhealer** [comment]
With an empty inventory, Fatal Frame still took an [ItemUnlocked] screenshot upon logging in.
I have also tried disabling all custom repo plugins, which did not solve the issue either.

For reference, if it can be of any help, these are my installed plugins:

### Official repo

- Acquisition Date
- Allagan Item Search
- Better borderless window mode
- CurrencyAlert
- DailyDuty
- Death Recap
- EnemyListDebuffs
- EngageTimer
- ezMiniCactpot
- Fader Plugin
- Fatal Frame
- Glamaholic
- JustBackup
- Monster Loot Hunter
- NoSoliciting
- Orchestrion Plugin
- PingPlugin
- QoL Bar
- Redirect
- RepairMe
- RezPlz
- Simple Tweaks Plugin
- Sonar
- SoundSetter
- Teleporter
- Which Patch Was That?
- Wotsit
- XIV Instant Messenger

### Custom repo

- Artisan
- AutoHook
- AutoRetainer
- Customize+
- Gatherbuddy Reborn
- Glamourer
- Heliosphere
- LazyLoot
- Lifestream
- Mare Synchronos
- Moodles
- NoClippy
- Palace Pal
- Pandora's Box
- Penumbra
- Reborn Toolbox
- Saucy
- SelectString
- Simple Heels
- Splatoon
- V(ery) Island
- vnavmesh
- Yes Already

**Comment by Glyceri** [comment]
Yes, I have figured out why this happens. A new update has been pushed but it might take some time before dalamud approves it. Version 1.0.1.1 should fix it.

**Comment by Glyceri** [comment]
Yes this issue definitely seems fixed

**Comment by Sunhealer** [comment]
Sweet! Thanks a lot!
